---
title: "4. GSEA"
author: "Runshan Gui"
date: "`r Sys.Date()`"
output: html_document
---

### 1.Clear the Environment
```{r}
rm(list=ls())
```

### 2.Loading Required Packages for GSEA
```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(ggplot2)
library(readxl)
library(dplyr)
library(msigdbr)
library(limma)
library(DESeq2)
```

### 3.Reading the File
```{r}
data <- read_excel("GSEA-GSE296602.xlsx", col_names = TRUE)
## Gene name conversion
gene_ensg <- mapIds(org.Hs.eg.db,
                    keys = data$Gene,
                    keytype = "ENSEMBL",
                    column = "SYMBOL",
                    multiVals = "first"
                    )
gene_map_df <- data.frame(
  ensg = names(gene_ensg),
  gene_name = unname(gene_ensg),
  stringsAsFactors = FALSE
  )
data <- data %>%
  left_join(gene_map_df, by = c("Gene" = "ensg"))
## DESeq2 normalization of count values
sample_info <- data.frame(
  condition = rep(c("Control", "TNFa"), each = 3))
dds <- DESeqDataSetFromMatrix(
  countData = data[, 2:7],  # Select count data columns
  colData = sample_info,
  design = ~ condition)
# Variance stabilizing transformation
vsd <- vst(dds, blind = FALSE)
vsd_data <- assay(vsd)
# Prepare GSEA input file
data <- data.frame(
  NAME = data$gene_name,
  vsd_data)
```

### 4.Data Preprocessing
```{r}
colnames(data)[1] <- "gene_name"
data_clean <- data[!data$gene_name %in% c("-", "", " ", NA), ]
cat("Dimensions after removing rows with gene name '-':", dim(data_clean), "\n")
```

### 5.Preparing the Expression Matrix
```{r}
expr_cols <- 2:7
expr_data <- as.matrix(data_clean[, 2:7])
rownames(expr_data) <- data_clean$gene_name
sample_names <- colnames(data_clean)[expr_cols]
colnames(expr_data) <- sample_names
expr_data <- apply(expr_data, 2, as.numeric)
rownames(expr_data) <- data_clean$gene_name
## Create group information
current_colnames <- colnames(data_clean)[2:7]
group_from_colnames <- ifelse(grepl("^Con", current_colnames), "Control", "Treatment")
group <- factor(group_from_colnames)
design <- model.matrix(~ group)
```

### 6.Differential Expression Analysis
```{r}
fit <- lmFit(expr_data, design)
fit <- eBayes(fit)
de_results <- topTable(fit, coef = 2, number = Inf, sort.by = "p")
```

### 7.Preparing GSEA Input Data
```{r}
gene_list <- de_results$logFC
names(gene_list) <- rownames(de_results)
gene_list <- na.omit(gene_list)
gene_list <- sort(gene_list, decreasing = TRUE)
```

### 8.Preprocessing for AMPK Pathway GSEA Analysis
```{r}
## Obtain the AMPK pathway gene list
significant_genes <- de_results[de_results$P.Value < 0.05, ]
ampk_kegg_genes <- enrichKEGG(gene = rownames(significant_genes),
                              organism = "hsa",
                              pvalueCutoff = 0.05,
                              qvalueCutoff = 0.05
                              )
ampk_gene_ids <- ampk_kegg_genes@geneSets[["hsa04152"]]
ampk_gene_symbols <- bitr(ampk_gene_ids,
                          fromType = "ENTREZID",
                          toType = "SYMBOL",
                          OrgDb = org.Hs.eg.db
                          )
matched_genes <- ampk_gene_symbols$ENTREZID[ampk_gene_symbols$ENTREZID %in% names(gene_list)]
cat("After re-matching, the number of AMPK genes in the gene list:", length(matched_genes), "\n")
```

### 9.Formal GSEA Analysis
```{r}
ampk_gene_set <- data.frame(
  gs_name = "AMPK_Signaling_Pathway_KEGG",
  gene_symbol = ampk_gene_ids
  )
custom_gsea2 <- GSEA(geneList = gene_list,
                     TERM2GENE = ampk_gene_set,
                     pvalueCutoff = 1,
                     nPerm = 10000,
                     minGSSize = 5,
                     maxGSSize = 500,
                     verbose = TRUE
                     )
pic <- gseaplot2(custom_gsea2, 
                 geneSetID = 1,
                 title = "AMPK Signaling Pathway GSEA",
                 color = "red",
                 pvalue_table = TRUE,
                 ES_geom = "line"
                 )
```

